# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  optimizer = true
  optimizer_runs = 5000
  out = "out"
  solc = "0.8.29"

[profile.airdrops]
  src = "airdrops"
  test = "airdrops"

[profile.flow]
  src = "flow"
  test = "flow"

[profile.lockup]
  src = "lockup"
  test = "lockup"

[lint]
  lint_on_build = false

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  ethereum = "https://direct.routeme.sh/rpc/1/${ROUTEMESH_API_KEY}"
